export const RouteNames = {
  MAIN: 'MAIN',
  PROFILE: 'PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  USER: 'USER',
  LOGIN: 'LOGIN',
  SETTINGS: 'SETTINGS',
  PRIVACY: 'PRIVACY',
  FORBIDDEN: 'FORBIDDEN',
  DECKS: 'DECKS',
  DECK: 'DECK',
  ALL_WORDS: 'ALL_WORDS',
  FLASHCARDS: 'FLASHCARDS',
  LEARN: 'LEARN',
  // last
  NOT_FOUND: 'NOT_FOUND',
} as const;
