export enum Accesses {
    administration = 'administration',

    users_can_create = "users_can_create",
    users_can_read = "users_can_read",
    users_can_update = "users_can_update",
    users_can_delete = "users_can_delete",

    groups_can_create = "groups_can_create",
    groups_can_read = "groups_can_read",
    groups_can_update = "groups_can_update",
    groups_can_delete = "groups_can_delete",
    groups_can_add_users = "groups_can_add_users",
    groups_can_read_users = "groups_can_read_users",
    groups_can_update_user_members = "groups_can_update_user_members",
    groups_can_remove_users = "groups_can_remove_users",

    documents_can_create = "documents_can_create",
    documents_can_read = "documents_can_read",
    documents_can_read_drafts = "documents_can_read_drafts",
    documents_can_search = "documents_can_search",
    documents_can_search_titles = "documents_can_search_titles",
    documents_can_update = "documents_can_update",
    documents_can_delete = "documents_can_delete",
    documents_can_restore = "documents_can_restore",
    documents_can_restore_from_revision = "documents_can_restore_from_revision",
    documents_can_publish = "documents_can_publish",
    documents_can_unpublish = "documents_can_unpublish",
    documents_can_move = "documents_can_move",
    documents_can_duplicate = "documents_can_duplicate",
    documents_can_add_user_members = "documents_can_add_user_members",
    documents_can_read_user_members = "documents_can_read_user_members",
    documents_can_update_user_members = "documents_can_update_user_members",
    documents_can_remove_user_members = "documents_can_remove_user_members",
    documents_can_add_group_members = "documents_can_add_group_members",
    documents_can_read_group_members = "documents_can_read_group_members",
    documents_can_update_group_members = "documents_can_update_group_members",
    documents_can_remove_group_members = "documents_can_remove_group_members",

    collections_can_create = "collections_can_create",
    collections_can_read = "collections_can_read",
    collections_can_search = "collections_can_search",
    collections_can_read_documents = "collections_can_read_documents",
    collections_can_reorder_documents = "collections_can_reorder_documents",
    collections_can_update = "collections_can_update",
    collections_can_delete = "collections_can_delete",
    collections_can_add_user_members = "collections_can_add_user_members",
    collections_can_read_user_members = "collections_can_read_user_members",
    collections_can_update_user_members = "collections_can_update_user_members",
    collections_can_remove_user_members = "collections_can_remove_user_members",
    collections_can_add_group_members = "collections_can_add_group_members",
    collections_can_read_group_members = "collections_can_read_group_members",
    collections_can_update_group_members = "collections_can_update_group_members",
    collections_can_remove_group_members = "collections_can_remove_group_members",

    files_can_create = "files_can_create",
    files_can_read = "files_can_read",

    revisions_can_read = "revisions_can_read",
    revisions_can_update = "revisions_can_update",
    revisions_can_delete = "revisions_can_delete",

    comments_can_create = "comments_can_create",
    comments_can_read = "comments_can_read",
    comments_can_update = "comments_can_update",
    comments_can_delete = "comments_can_delete",
    comments_can_resolve = "comments_can_resolve",
    comments_can_react = "comments_can_react",

    stars_can_create = "stars_can_create",
    stars_can_read = "stars_can_read",
    stars_can_update = "stars_can_update",
    stars_can_delete = "stars_can_delete",

    documents_can_read_templates = "documents_can_read_templates",
    documents_can_templatize = "documents_can_templatize",
    documents_can_read_deleted = "documents_can_read_deleted",
    documents_can_empty_trash = "documents_can_empty_trash",
}
